[build-system]
requires = ["setuptools>=62.6"]
build-backend = "setuptools.build_meta"

[project]
name = "connect-hub-api"
version = "0.1.0"
requires-python = ">=3.9, <3.13"
dynamic = ["dependencies"]

[tool.uv]
package = false

[tool.setuptools]
package-dir = { "" = "." }

[tool.setuptools.packages.find]
where = ["."]
include = ["app"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.fastapi]
entrypoint = "app.main:app"
