"""add share col

Revision ID: 1bfbd156be08
Revises: 8d4f2b1c3e5a
Create Date: 2026-08-29 01:36:25.479076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfbd156be08'
down_revision: Union[str, None] = '8d4f2b1c3e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_shared_post_id'), 'posts', ['shared_post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_shared_post_id'), table_name='posts')
    # ### end Alembic commands ###
