"""add_comment_replies_and_reaction_type

Revision ID: b8873e33f8d5
Revises: 1bfbd156be08
Create Date: 2026-08-29 02:26:03.914666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8873e33f8d5'
down_revision: Union[str, None] = '1bfbd156be08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
